# Generated by Django 6.1 on 2026-08-15

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = []

    operations = [
        migrations.CreateModel(
            name="CatalogBook",
            fields=[
                ("catalog_id", models.CharField(max_length=16, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("alternate_titles", models.JSONField(blank=True, default=list)),
                ("author_aliases", models.JSONField(blank=True, default=list)),
                ("edition", models.CharField(blank=True, max_length=255)),
                ("contained_titles", models.JSONField(blank=True, default=list)),
            ],
            options={"ordering": ("catalog_id",)},
        ),
    ]
